Minor spelling fixes, updated booster query
JeroenoBoy/PSWrapper pull request #2
Opened 2020-09-30 20:56 UTC by DebitCardz

You can now specify how many servers you would like to query when using top boosters, example being you can get the top 5 boosted servers or just the top.

2020-09-30 21:01 UTC, JeroenoBoy requested changes
This will break the wrapper, server.js line 9

2020-09-30 21:02 UTC, DebitCardz commented
Issue resolved, my mistake.

2020-09-30 23:16 UTC, unlimitedcoder2 commented
![20200821_010331-1-1-1-1-1-3](https://user-images.githubusercontent.com/16884313/94749282-60832400-037b-11eb-914e-d4d2277d7de2.jpg)

2020-10-01 01:54 UTC, DebitCardz commented
please query that booster alex howadeasra

2020-10-01 09:52 UTC, JeroenoBoy commented
After further inspections (aka not on my phone), these changes are inefficient / not required.

2020-10-01 09:52 UTC, closed without merging

2020-10-02 20:06 UTC, unlimitedcoder2 commented on src/groups/servers.js
> -		const { server_count } = await retrieveData();
this literally breaks it lol @DebitCardz